/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.equipo2.inventario.view;

import es.equipo2.inventario.controller.BusquedaController;
import es.equipo2.inventario.model.Objeto;
import java.awt.*;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 * Panel de busqueda
 * @author DAW104
 */
public class BusquedaPanel extends javax.swing.JPanel {

    private BusquedaController controller = new BusquedaController();
    private JTextField txtNombre, txtCodigo, txtCategoria, txtEstado;
    private JTable tabla;
    private DefaultTableModel modeloTable;
    private JLabel lblResultados;
    
    /**
     * Creates new form BusquedaPanel
     */
    public BusquedaPanel() {
        initComponents();
        myInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myInitComponents(){
        setLayout(new BorderLayout(0, 0));
        setBackground(Estilo.GRIS_FONDO);
        
        JPanel norte = new JPanel(new BorderLayout());
        norte.add(Estilo.barraHeader("🔍  Busqueda y Localizacion"), BorderLayout.NORTH);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
