db.url=jdbc:mysql://localhost:5433/inventario?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Madrid
db.usuario=admin
db.clave=usuario@1
db.useSSL=false
db.serverTimezone=Europe/Madrid 